version: '3'

services:

  neo4j:
    build: ./neo4j/v3.5.x
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true

  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - GRAPHQL_LISTEN_PORT=8000
      - GRAPHQL_URI=http://localhost:8000/graphql
    volumes:
      # Map our local directory to the Docker container so our changes can immediately take effect
      - ./server/src:/app/src
      # Use the node_modules installed on the Docker image
      - /app/node_modules
    links:
    - neo4j
    depends_on:
    - neo4j

  app:
    build: ./app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPHQL_URI=http://localhost:8000/graphql
      - PROXY=http://localhost:8000/graphql
    links:
    - server
    depends_on:
    - server
